apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-ms
  template:
    metadata:
      labels:
        app: image-ms
    spec:
      containers:
        - image: rsolinux/image-ms:2020-10-30-02-45-03
          name: image-ms
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://otto.db.elephantsql.com:5432/jrickhfw
            - name: SPRING_DATASOURCE_USERNAME
              value: jrickhfw
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: image-ms
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-ms
