apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-ms
  template:
    metadata:
      labels:
        app: image-ms
    spec:
      containers:
        - image: rsolinux/image-ms:latest
          name: image-ms
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/pblmowui
            - name: SPRING_DATASOURCE_USERNAME
              value: pblmowui
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: image-pg-pass
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: image-ms
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: image-ms
